config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#index'

  resources :chatroom do
    member do
      post 'send_message'
      get :events
    end
  end

end

app/models/chatroom.rb
require 'securerandom'

class Chatroom < ActiveRecord::Base
  belongs_to :user
  has_many :messages


# Class methods

  def self.create_with_creator(creator)
    random_UUID = SecureRandom.base64
    creator.chatrooms.create(uniqueURL: random_UUID)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chatroom

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chatrooms
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: :index

  # adds params for devise
  before_action :configure_permitted_parameters, if: :devise_controller?


  def index
              
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  include ActionController::Live

  before_action :authenticate_user!

  def show
    @room = Chatroom.find(params[:id]) 
    @messages = @room.messages
  end

  def create
    @room = Chatroom.create_with_creator(current_user)
    redirect_to chatroom_url(@room)
  end

  def send_message
    @room = Chatroom.find(params[:id])
    message = Message.create(message_params)
    @room.messages << message
    current_user.messages << message
    redirect_to :back
  end

  def events
    room = Chatroom.find(params[:id]) 
    response.headers["Content-Type"] = "text/event-stream"
    # start = Time.zone.now
    messages = room.messages.filter( |m| m.created_at > start)
    room.messages.each do |message|
      response.stream.write "data: #{message.text}\n\n"
    end 
  rescue IOError
    logger.info "Stream closed"
  ensure
    response.stream.close
  end


private

  def message_params
    params.require(:message).permit(:text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-error"
      when "alert" then "alert alert-error"
    end
  end

end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/application/index.html.erb
<div class="jumbotron">
  <h1> Sorta Like IRC</h1>
  <p> Click on the button below to instantly create a new chatroom and invite your friends.</p>
  <%= button_to "Create", chatroom_index_path, class: "btn btn-primary", method: "POST" %>
</div>

app/views/chatroom/show.html.erb
<div class="page-header">
  <h1><%= @room.user.username + "'s " %>Chatroom <small>invite your friends for an instant place to chat</small></h1>
  <p> Link: <%= @room.uniqueURL %> </p>
</div>
<table class="table">
    <tbody>
      <% @messages.each do |m| %>
        <tr>
          <td><%= m.user.username %></td>
          <td><%= m.text %></td>
        </tr>  
      <% end %>
      
    </tbody>
</table>
<%= form_for :message, url: {action: :send_message }, html: {class: "form-inline", role: "form" } do |f| %>
<div class="row">
  <div class="col-lg-12">
    <div class="input-group">
      <%= f.text_field :text, class: "form-control", placeholder: "message" %>
      <span class="input-group-btn">
        <%= f.submit "send", class: "btn btn-default"  %>
      </span>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SLIRC", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
      <%#   <li><a href="#">Link</a></li>%>
      <%#   <li class="dropdown">%>
      <%#     <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>%>
      <%#     <ul class="dropdown-menu">%>
      <%#       <li><a href="#">Action</a></li>%>
      <%#       <li><a href="#">Another action</a></li>%>
      <%#       <li><a href="#">Something else here</a></li>%>
      <%#       <li class="divider"></li>%>
      <%#       <li><a href="#">Separated link</a></li>%>
      <%#       <li class="divider"></li>%>
      <%#       <li><a href="#">One more separated link</a></li>%>
      <%#     </ul>%>
      <%#   </li>%>
      </ul>
      <%# <form class="navbar-form navbar-left" role="search">%>
      <%#   <div class="form-group">%>
      <%#     <input type="text" class="form-control" placeholder="Search">%>
      <%#   </div>%>
      <%#   <button type="submit" class="btn btn-default">Submit</button>%>
      <%# </form>%>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
          <% else %>
              <%= link_to "Sign In", new_user_session_path %>
          <% end %>

          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slirc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "layouts/navbar" %>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>

</body>
</html>